spring.application.name=sougou

# DB(dockerコンテナ内 PostgreSQL)連携
spring.datasource.url=jdbc:postgresql://localhost:5432/training
spring.datasource.username=docker
spring.datasource.password=docker
spring.datasource.driver-class-name=org.postgresql.Driver

# SQLをコンソール出力
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# エンティティの構成をDBに自動作成
spring.jpa.hibernate.ddl-auto=update

spring.sql.init.mode=always